learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "learn"
urlpatterns = [
    path('', view=views.CourseListView.as_view(), name='index'),
    path('<int:course_id>/enroll/', views.EnrollView.as_view(), name='enroll'),
    path('<int:pk>/', views.CourseDetailsView.as_view(), name='course_details'),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegistrationView.as_view(), name="registration"),
    path('result/<int:pk>', views.ExamResultView.as_view(), name="result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learndjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("learn/", include("learn.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learn/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + \
            self.occupation


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    grade = models.FloatField(default=1.0)

    def is_correct(self, selected_choice_ids):
        selected_correct_choices = self.choice_set.filter(
            is_correct=True, id__in=selected_choice_ids).count()
        selected_choices = self.choice_set.filter(
            id__in=selected_choice_ids).count()
        return selected_correct_choices == selected_choices


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)


class Submission(models.Model):
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)

learn/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import generic, View
from django.http import Http404
from django.contrib.auth import login, logout, authenticate
import logging
logger = logging.getLogger(__name__)

# Create your views here.


class EnrollView(View):
    def post(self, request, *args, **kwargs):
        course_id = kwargs.get('course_id')
        user = request.user
        if not user.is_authenticated:
            return HttpResponseRedirect(reverse(viewname='learn:login'))

        course = get_object_or_404(Course, pk=course_id)
        is_enrolled = check_if_enrolled(user, course)
        if not is_enrolled and user.is_authenticated:
            # Create an enrollment
            Enrollment.objects.create(user=user, course=course, mode='honor')
            course.total_enrollment += 1
            course.save()

        return HttpResponseRedirect(reverse(viewname='learn:course_details', args=(course.id,)))


class CourseListView(generic.ListView):
    template_name = 'learn/course_list.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)
        return courses


class CourseDetailsView(generic.DetailView):
    model = Course
    template_name = "learn/course_details.html"


def logout_request(request):
    print("Logout the user `{}`".format(request.user.username))
    logout(request)
    return redirect("learn:index")


class LoginView(View):
    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        password = request.POST["psw"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("learn:index")
        else:
            return render(request, "learn/user_login.html", {})

    def get(self, request, *args, **kwargs):
        return render(request, "learn/user_login.html", {})


class RegistrationView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "learn/user_registration.html", {})

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            user.save()
            login(request, user)
            return redirect("learn:index")
        else:
            return render(request, 'learn/user_registration_bootstrap.html', {"message": "User already exists."})


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        # Check if user enrolled
        num_results = Enrollment.objects.filter(
            user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


class ExamResultView(View):
    def post(self, request, *args, **kwargs):
        # Get the current user and the course object, then get the associated the enrollment object
        course_id = kwargs.get('pk')
        user = request.user
        course = get_object_or_404(Course, pk=course_id)
        enrollment = course.enrollment_set.get(user=user)

        # Create a new submission object referring to the enrollment
        submission = Submission.objects.create(enrollment=enrollment)

        # Collect the selected choices from HTTP request object
        answers = self.extract_answers(request)

        # Add each selected choice object to the submission object
        submission.choices.clear()
        for answer in answers:
            choice = get_object_or_404(Choice, pk=answer)
            submission.choices.add(choice)

        # Redirect to a show_exam_result view with the submission id to show the exam result
        return HttpResponseRedirect(reverse(viewname='learn:result', args=(submission.id,)))

    def extract_answers(self, request):
        return [int(v) for k, v in request.POST.items() if k.startswith("choice")]

    def get(self, request, *args, **kwargs):
        # Get the course object and submission object based on their ids in view arguments
        submission_id = kwargs.get('pk')
        submission = get_object_or_404(Submission, pk=submission_id)

        # Get the selected choice ids from the submission record
        choices = submission.choices.all()
        choice_id = [choice.id for choice in choices]

        # For each selected choice, check if it is a correct answer or not
        # Calculate the total score by adding up the grades for all questions in the course
        score = self.calculate_score(submission)
        total_possible_score = self.get_total_possible_score(
            submission.enrollment.course)

        # Add the course, selected_ids, and grade to context for rendering HTML page
        return render(
            request,
            "learn/exam_result.html",
            {
                "course": submission.enrollment.course,
                "selected_choice_ids": choice_id,
                "score": score,
                "total_possible_score": total_possible_score,
                "passed": (score/total_possible_score) > 0.5
            }
        )

    def get_total_possible_score(self, course):
        questions = course.question_set.all()
        total_score = 0
        for question in questions:
            total_score += question.grade
        return total_score

    def calculate_score(self, submission):
        score = 0
        questions = submission.enrollment.course.question_set.all()
        selected_ids = [choice.id for choice in submission.choices.all()]
        for question in questions:
            if question.is_correct(selected_ids):
                score += question.grade
        return score

learn/templates/learn/course_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8" />
  </head>

  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'learn:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'learn:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'learn:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Username"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a class="btn btn-link" href="{% url 'learn:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">
      <h2>{{ course.name }}</h2>
      <div class="card-columns-vertical">
        {% for lesson in course.lesson_set.all %}
        <div class="card mb-3">
          <div class="card-header">
            <h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5>
          </div>
          <div class="card-body">{{lesson.content}}</div>
        </div>
        {% endfor %} {% if user.is_authenticated %}
        <div>
          <button
            class="btn btn-primary"
            data-toggle="collapse"
            data-target="#questions{{lesson.id}}"
            aria-expanded="false"
            aria-controlse="collapseQuestions"
          >
            Start Exam
          </button>
          <div class="collapse" id="questions{{lesson.id}}">
            <hr />
            <h2>{{ course.name }} Exam</h2>
            <form action="{% url 'learn:result' course.id %}" method="POST">
              {% csrf_token %}
              <div>
                {% for question in course.question_set.all %}
                <div class="card mb-3">
                  <div class="card-header">
                    <h5 class="card-title">
                      Q{{ forloop.counter }}: {{ question.text }}
                    </h5>
                  </div>
                  <div class="card-body">
                    <div class="list-group list-group-flush">
                      {% for choice in question.choice_set.all%}
                      <div class="list-group-item">
                        <input
                          name="choice-{{choice.id}}"
                          type="checkbox"
                          id="choice-{{choice.id}}"
                          value="{{choice.id}}"
                        />
                        <label for="choice-{{choice.id}}">
                          {{choice.text}}
                        </label>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
              <button class="btn btn-success" type="submit">Submit</button>
            </form>
          </div>
        </div>
        {% endif %}
      </div>

      <!-- Task: show questions and choices -->
      <!-- <HINT> Use Bootstrap Collapse to hide exam first, more details could be found here
            https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp-->

      <!--

            A collapse example here:
            <div id="exam" class="collapse">
                Click to expand elements within the collapse div
                </div>

            -->

      <!-- <HINT> If user is authenticated, show course exam with a list of question -->

      <!-- <HINT> Each example will have many questions -->

      <!-- <HINT> Each question will have many choices -->

      <!-- <HINT> Create a form to collect the selected choices for all questions -->
      <!-- <HINT> For each question choice, you may create a checkbox input like
            <input type="check" name="choice_{{choice.id}}" id="{{choice.id}}" ...>
            -->

      <!-- A choice submission form example
            <form id="questionform" action="point to a submit view" method="post">
                        ... for each question in the course ...
                        <div class="card mt-1">
                            <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                            {% csrf_token %}
                            <div class="form-group">
                               ... for each choice in the question ...
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="choice_{{choice.id}}"
                                               class="form-check-input" id="{{choice.id}}"
                                               value="{{choice.id}}">{{ choice.choice_text }}
                                    </label>
                                </div>
                            </div>
                        </div>
                    <input class="btn btn-success btn-block" type="submit" value="Submit">
            </form> -->

      <!--Check here to see more details Bootstrap checkbox
             https://www.w3schools.com/bootstrap4/bootstrap_forms_inputs.asp-->
    </div>
  </body>
</html>

learn/templates/learn/course_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <meta charset="UTF-8" />
    <title>Online Courses</title>
  </head>
  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Online Course</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'learn:logout' %}"
              >Logout</a
            >
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'learn:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Username"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'learn:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Page content -->
    {% if course_list %}
    <div class="container">
      <div class="card-deck">
        {% for course in course_list %}
        <div class="card" style="width: 36rem">
          <img
            class="card-img-left"
            src="{{MEDIA_URL}}/{{ course.image }}"
            width="240px"
            height="240px"
            alt="Course image"
          />
          <div class="card-body bg-light">
            <h5 class="card-title">
              {{ course.name }},
              <span class="text-success">
                {{ course.total_enrollment}} enrolled</span
              >
            </h5>
            <p class="card-text">{{ course.description}}</p>
            <form
              action="{% url 'learn:enroll' course.id %}"
              method="post"
            >
              {% csrf_token %}
              <input
                class="btn btn-primary"
                type="submit"
                value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} "
              />
            </form>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <p>No courses are available.</p>
    {% endif %}
  </body>
</html>

learn/templates/learn/exam_result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8" />
  </head>

  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'learn:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'learn:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'learn:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Username"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'learn:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">
      <h2>{{ course.name }} Exam Results</h2>
      {% if passed %}
      <div class="alert alert-success" role="alert">
        <strong>Congragulations, {{ user.first_name }}!</strong> You have passed
        the exam with a score of {{score}}/{{total_possible_score}}.
      </div>
      {% else %}
      <div class="alert alert-danger" role="alert">
        <strong>Failed!</strong> Sorry {{ user.first_name }}, you failed the
        exam with a score of {{score}}/{{total_possible_score}}.
      </div>
      {% endif %} {% for question in course.question_set.all %}
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Q{{ forloop.counter }}: {{ question.text }}
          </h3>
        </div>
        <div class="card-body">
          <div class="list-group list-group-flush">
            {% for choice in question.choice_set.all%}
            <div class="list-group-item">
              {% if choice.is_correct and choice.id in selected_choice_ids%}
              <p class="text-success">Correct answer: {{ choice.text }}</p>
              {% elif choice.is_correct and choice.id not in selected_choice_ids%}
              <p class="text-warning">Not selected: {{ choice.text }}</p>
              {% elif not choice.is_correct and choice.id in selected_choice_ids%}
              <p class="text-danger">Your Answer: {{ choice.text }}</p>
              {% else %}
              <p>{{ choice.text }}</p>
              {% endif %}
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

learn/templates/learn/user_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'learn/course.css' %}"
    />
    <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  />
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Online Course</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'learn:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'learn:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a class="btn btn-link" href="{% url 'learn:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <form action="{% url 'learn:login' %}" method="post">
      {% csrf_token %}
      <div class="container">
        <!--Style root div with .container class -->
        <h1>Login</h1>
        <div class="form-group">
          <!--Style second div with .form-group class -->
          <label for="username"><b>User Name</b></label>
          <input
            id="username"
            class="form-control"
            type="text"
            placeholder="Enter User Name: "
            name="username"
            required
          />
          <!--Style input with .form-control class -->
          <label for="psw"><b>Password</b></label>
          <input
            id="psw"
            class="form-control"
            type="password"
            placeholder="Enter Password: "
            name="psw"
            required
          />
          <!--Style input with .form-control class -->
        </div>
        {% if message %}
        <div class="alert alert-warning">
          <!--Style the message paragraph with .alert and .alert-warning class -->
          {{ message }}
        </div>
        {% endif %}
        <button class="btn btn-primary" type="submit">Login</button>
        <!--Style button with .btn and .btn-primary class -->
      </div>
    </form>
  </body>
</html>

learn/templates/learn/user_registration.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'learn/course.css' %}"
    />
    <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  />
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Online Course</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'learn:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'learn:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a class="btn btn-link" href="{% url 'learn:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <form action="{% url 'learn:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
          {% csrf_token %}
          <h1>Sign Up</h1>
          <hr>
          <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="firstname"><b>First Name</b></label>
              <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
              <label for="lastname"><b>Last Name</b></label>
              <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
              {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                  {{ message }}
              </div>
              {% endif %}
              <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
          </div>
        </div>
      </form>
  </body>
</html>